[package]
name = "shalltear"
version = "0.1.0"
authors = ["#name <#email>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
futures = "0.1"
tokio-core = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
sha2 = "0.7"
hmac = "0.5"
hex = "0.3"

